# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BugFenderExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BugFenderExample
  pod 'BugfenderSDK/ObjC'

  target 'BugFenderExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BugFenderExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BugFenderExample-tvOS

  target 'BugFenderExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
